_wandb:
    value:
        cli_version: 0.22.2
        e:
            ymxlryhm8undhohf1bqb9uvdjy1utcpi:
                codePath: notebooks/paper_figures.ipynb
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "924758052864"
                        used: "725146742784"
                email: adele@ucsb.edu
                executable: /home/adele/anaconda3/envs/gagf/bin/python
                git:
                    commit: e0f0ceab9c838116eea0226d2f5e4ef24bba5cd2
                    remote: git@github.com:geometric-intelligence/group-agf.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-4b49ab48-3033-b858-ccf4-877f11ad24a5
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-9573e3b6-419b-ed26-f7fa-3a5e9d8cbb67
                host: bongo
                memory:
                    total: "1082004721664"
                os: Linux-5.15.0-151-generic-x86_64-with-glibc2.35
                program: /home/adele/group-agf/notebooks/paper_figures.ipynb
                python: CPython 3.12.12
                root: /home/adele/group-agf/gagf
                startedAt: "2025-10-31T18:48:58.659185Z"
                writerId: ymxlryhm8undhohf1bqb9uvdjy1utcpi
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 15
                - 17
            "4": 3.12.12
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 128
dataset_fraction:
    value: 0.3
epochs:
    value: 5000
full_run:
    value: true
group:
    value: Octahedral
group_name:
    value: octahedral
group_size:
    value: 24
init_scale:
    value: 0.01
lr:
    value: 0.01
mom:
    value: 0.9
run_start_time:
    value: 10-31_11-48-56
seed:
    value: 10
verbose_interval:
    value: 100
